apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.db }}"
          ports:
            - name: postgres
              containerPort: {{ .Values.service.port }}
              protocol: TCP

