apiVersion: v1
kind: Service
metadata:
  name: cast-db
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cast-db
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: postgres
